[project]
name = "firestore-schema-dump"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-cloud-firestore>=2.20.2",
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
]
